Complete Lesson 14
Dmitriy2077/TMS_Homework14 pull request #1
Opened 2021-12-09 13:30 UTC by Dmitriy2077

2021-12-09 14:43 UTC, Sigezmund requested changes

2021-12-09 14:43 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/CalculatorActivity.kt
> +                operatorButton!![0]?.id -> operand!!.add()
Вместо !! лучше использовать безопасный вызов ?. там, где это возможно

2021-12-09 14:43 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +            1 -> getString(answer[0])
Возможно тут не нужен никакой when, попробуй найти, как связаны между собой правая и левая часть

2021-12-09 14:43 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +        val randomAnswer = (1..6).random()
попробуй привязаться к размеру листа

2021-12-09 14:43 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +            listOf(0, 1, 2, 3).asSequence().shuffled().take(it.size).toList()
Не совсем понимаю что тут происходит)

2021-12-09 14:43 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +        answerBtn!!.forEach {
посмотри метод forEachIndexed

2021-12-09 14:43 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +            answerBtnLT -> {
Лучше сравнивать по id

2021-12-09 14:43 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +                    it!!.visibility = if (it == answerBtnLT) Button.VISIBLE else Button.INVISIBLE
Не уверен, что правильно понял, но мне кажется тут не нужен when

2022-01-06 17:05 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/CalculatorActivity.kt
> +                operatorButton!![0]?.id -> operand!!.add()
Я попробовал через lateinit убрать "!!." и "?.".

2022-01-06 17:05 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +            1 -> getString(answer[0])
Урал этот "when", он оказался совсем лишним

2022-01-06 17:05 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +        val randomAnswer = (1..6).random()
Исправлено.

2022-01-06 17:05 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +            listOf(0, 1, 2, 3).asSequence().shuffled().take(it.size).toList()
Это я придумал, чтобы ответы в кнопках каждый раз менялись местами. Если это убрать, то ответы на вопросы будут закреплены за определенными кнопками. При рандоме, ответы могут дублироваться или может не попасться правильный. Может это можно по-другому сделать?

2022-01-06 17:06 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +                    it!!.visibility = if (it == answerBtnLT) Button.VISIBLE else Button.INVISIBLE
Исправил, здесь всё работает и без него

2022-01-06 17:06 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +            answerBtnLT -> {
Выполнил

2022-01-06 17:07 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +        answerBtn!!.forEach {
Применил, но в другом месте(строка 87)

2022-01-16 21:34 UTC, Sigezmund requested changes

2022-01-16 21:34 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/CalculatorActivity.kt
> +        operatorButton = listOf(
мне кажется, этот массив не несет никакого смысла)

2022-01-16 21:34 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +        R.string.magicBallA_7th
Лучше вынести последний вариант(ошибка ввода) из массива и не завязываться на его индекс. Если ты добавишь еще пару сообщений изменения придется делать в двух местах.
Тут

2022-01-16 21:34 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +            if (magicQuestion!!.text.isNotEmpty()) getString(answer[randomAnswer]) else getString(answer[6])
И тут)

2022-01-16 21:34 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +            listOf(0, 1, 2, 3).asSequence().shuffled().take(it.size).toList()
Понял, хорошая идея, но я думаю, что тут sequence не нужна, а listOf можно заменить на  (0..riddles.size)

2022-01-16 21:34 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/CalculatorActivity.kt
> +                firstNumber.text.toString().toFloat(),
Крэшит, если ввести только точку или минус

2022-01-17 16:42 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/CalculatorActivity.kt
> +        operatorButton = listOf(
Ну да, это просто красивая обертка. Я это убрал

2022-01-18 14:46 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +        R.string.magicBallA_7th
Исправлено здесь.

2022-01-18 14:46 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/MagicBallActivity.kt
> +            if (magicQuestion!!.text.isNotEmpty()) getString(answer[randomAnswer]) else getString(answer[6])
И здесь тоже исправлено.

2022-01-18 15:14 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +            listOf(0, 1, 2, 3).asSequence().shuffled().take(it.size).toList()
Из  этого " val sequence = riddles?.let {listOf(0, 1, 2, 3).asSequence().shuffled().take(it.size).toList()" сделал
вот это "val sequence = riddles.indices.shuffled().take(riddles.size).toList()".
Как полностью избавиться от "sequence" и сохранить рандомные ответы без дублирования, я пока не понял

2022-01-19 16:52 UTC, Dmitriy2077 commented on app/src/main/java/com/lubinskiy/lesson14/modules/CalculatorActivity.kt
> +                firstNumber.text.toString().toFloat(),
Исправил, правда немного в функционале потерял

2022-01-23 20:24 UTC, Sigezmund commented on app/src/main/java/com/lubinskiy/lesson14/modules/RiddlesActivity.kt
> +            listOf(0, 1, 2, 3).asSequence().shuffled().take(it.size).toList()
Я имел ввиду, что не нужен метод asSequence(). И take там тоже лишний

2022-01-23 20:26 UTC, merged